[server]
enableStaticServing = true
enableCORS = true
corsAllowedOrigins = ["https://web.geolibre.app"]


[theme]
primaryColor = "#653F84"
backgroundColor = "#231134"
secondaryBackgroundColor = "#2b1642"
textColor = "#D7D2CB"
font = "sans serif"
